### ISSUE TITLE
[Feature Request] Separate example astro library from ASSET source code

### ISSUE THREAD

**Issue by jasonmeverett** [AlabamaASRL/asset_asrl#12]
Adding example libraries to a different repo will allow for minimalist installation of ASSET without example scripts if not needed. Will help eventually with:

* Separating out the true minimal files necessary for a conda install
* Smaller footprint for containerized applications

**Comment by jbpezent** [comment]
@jasonmeverett At present, I think we need to distribute with the asset_asrl.Astro library so that the software is up to spec with our original proposal. After we release version 1.0.0 at the conclusion of the contract at the end of this year, we can discuss with users and our NASA contact about how they feel about us separating ASSET into sub-libraries.
